// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: rpc.proto

package gctrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GoCryptoTraderService_GetInfo_FullMethodName             = "/gctrpc.GoCryptoTraderService/GetInfo"
	GoCryptoTraderService_GetRPCEndpoints_FullMethodName     = "/gctrpc.GoCryptoTraderService/GetRPCEndpoints"
	GoCryptoTraderService_GetAccounts_FullMethodName         = "/gctrpc.GoCryptoTraderService/GetAccounts"
	GoCryptoTraderService_GetTokenPrice_FullMethodName       = "/gctrpc.GoCryptoTraderService/GetTokenPrice"
	GoCryptoTraderService_Crypto_FullMethodName              = "/gctrpc.GoCryptoTraderService/Crypto"
	GoCryptoTraderService_TransferSOL_FullMethodName         = "/gctrpc.GoCryptoTraderService/TransferSOL"
	GoCryptoTraderService_TransferToken_FullMethodName       = "/gctrpc.GoCryptoTraderService/TransferToken"
	GoCryptoTraderService_StartAutoTrade_FullMethodName      = "/gctrpc.GoCryptoTraderService/StartAutoTrade"
	GoCryptoTraderService_StopAutoTrade_FullMethodName       = "/gctrpc.GoCryptoTraderService/StopAutoTrade"
	GoCryptoTraderService_BuySOLToken_FullMethodName         = "/gctrpc.GoCryptoTraderService/BuySOLToken"
	GoCryptoTraderService_StopSOLTokenMonitor_FullMethodName = "/gctrpc.GoCryptoTraderService/StopSOLTokenMonitor"
	GoCryptoTraderService_GetProfitLoss_FullMethodName       = "/gctrpc.GoCryptoTraderService/GetProfitLoss"
	GoCryptoTraderService_TradeTokenBySignal_FullMethodName  = "/gctrpc.GoCryptoTraderService/TradeTokenBySignal"
	GoCryptoTraderService_StopSignalMonitor_FullMethodName   = "/gctrpc.GoCryptoTraderService/StopSignalMonitor"
	GoCryptoTraderService_MonitorPrice_FullMethodName        = "/gctrpc.GoCryptoTraderService/MonitorPrice"
)

// GoCryptoTraderServiceClient is the client API for GoCryptoTraderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GoCryptoTraderServiceClient interface {
	GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error)
	GetRPCEndpoints(ctx context.Context, in *GetRPCEndpointsRequest, opts ...grpc.CallOption) (*GetRPCEndpointsResponse, error)
	GetAccounts(ctx context.Context, in *GetAccountsRequest, opts ...grpc.CallOption) (*GetAccountsResponse, error)
	GetTokenPrice(ctx context.Context, in *GetTokenPriceRequest, opts ...grpc.CallOption) (*GetTokenPriceResponse, error)
	Crypto(ctx context.Context, in *CryptoRequest, opts ...grpc.CallOption) (*CryptoResponse, error)
	TransferSOL(ctx context.Context, in *TransferSOLRequest, opts ...grpc.CallOption) (*TransferSOLResponse, error)
	TransferToken(ctx context.Context, in *TransferTokenRequest, opts ...grpc.CallOption) (*TransferTokenResponse, error)
	StartAutoTrade(ctx context.Context, in *StartAutoTradeRequest, opts ...grpc.CallOption) (*StartAutoTradeResponse, error)
	StopAutoTrade(ctx context.Context, in *StopAutoTradeRequest, opts ...grpc.CallOption) (*StopAutoTradeResponse, error)
	BuySOLToken(ctx context.Context, in *BuySOLTokenRequest, opts ...grpc.CallOption) (*BuySOLTokenResponse, error)
	StopSOLTokenMonitor(ctx context.Context, in *StopAutoTradeRequest, opts ...grpc.CallOption) (*StopAutoTradeResponse, error)
	GetProfitLoss(ctx context.Context, in *GetProfitLossRequest, opts ...grpc.CallOption) (*GetProfitLossResponse, error)
	TradeTokenBySignal(ctx context.Context, in *TradeTokenBySignalRequest, opts ...grpc.CallOption) (*TradeTokenBySignalResponse, error)
	StopSignalMonitor(ctx context.Context, in *StopSignalMonitorRequest, opts ...grpc.CallOption) (*StopSignalMonitorResponse, error)
	MonitorPrice(ctx context.Context, in *MonitorPriceRequest, opts ...grpc.CallOption) (*MonitorPriceResponse, error)
}

type goCryptoTraderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGoCryptoTraderServiceClient(cc grpc.ClientConnInterface) GoCryptoTraderServiceClient {
	return &goCryptoTraderServiceClient{cc}
}

func (c *goCryptoTraderServiceClient) GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInfoResponse)
	err := c.cc.Invoke(ctx, GoCryptoTraderService_GetInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goCryptoTraderServiceClient) GetRPCEndpoints(ctx context.Context, in *GetRPCEndpointsRequest, opts ...grpc.CallOption) (*GetRPCEndpointsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRPCEndpointsResponse)
	err := c.cc.Invoke(ctx, GoCryptoTraderService_GetRPCEndpoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goCryptoTraderServiceClient) GetAccounts(ctx context.Context, in *GetAccountsRequest, opts ...grpc.CallOption) (*GetAccountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAccountsResponse)
	err := c.cc.Invoke(ctx, GoCryptoTraderService_GetAccounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goCryptoTraderServiceClient) GetTokenPrice(ctx context.Context, in *GetTokenPriceRequest, opts ...grpc.CallOption) (*GetTokenPriceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTokenPriceResponse)
	err := c.cc.Invoke(ctx, GoCryptoTraderService_GetTokenPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goCryptoTraderServiceClient) Crypto(ctx context.Context, in *CryptoRequest, opts ...grpc.CallOption) (*CryptoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CryptoResponse)
	err := c.cc.Invoke(ctx, GoCryptoTraderService_Crypto_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goCryptoTraderServiceClient) TransferSOL(ctx context.Context, in *TransferSOLRequest, opts ...grpc.CallOption) (*TransferSOLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferSOLResponse)
	err := c.cc.Invoke(ctx, GoCryptoTraderService_TransferSOL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goCryptoTraderServiceClient) TransferToken(ctx context.Context, in *TransferTokenRequest, opts ...grpc.CallOption) (*TransferTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferTokenResponse)
	err := c.cc.Invoke(ctx, GoCryptoTraderService_TransferToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goCryptoTraderServiceClient) StartAutoTrade(ctx context.Context, in *StartAutoTradeRequest, opts ...grpc.CallOption) (*StartAutoTradeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartAutoTradeResponse)
	err := c.cc.Invoke(ctx, GoCryptoTraderService_StartAutoTrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goCryptoTraderServiceClient) StopAutoTrade(ctx context.Context, in *StopAutoTradeRequest, opts ...grpc.CallOption) (*StopAutoTradeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopAutoTradeResponse)
	err := c.cc.Invoke(ctx, GoCryptoTraderService_StopAutoTrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goCryptoTraderServiceClient) BuySOLToken(ctx context.Context, in *BuySOLTokenRequest, opts ...grpc.CallOption) (*BuySOLTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuySOLTokenResponse)
	err := c.cc.Invoke(ctx, GoCryptoTraderService_BuySOLToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goCryptoTraderServiceClient) StopSOLTokenMonitor(ctx context.Context, in *StopAutoTradeRequest, opts ...grpc.CallOption) (*StopAutoTradeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopAutoTradeResponse)
	err := c.cc.Invoke(ctx, GoCryptoTraderService_StopSOLTokenMonitor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goCryptoTraderServiceClient) GetProfitLoss(ctx context.Context, in *GetProfitLossRequest, opts ...grpc.CallOption) (*GetProfitLossResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProfitLossResponse)
	err := c.cc.Invoke(ctx, GoCryptoTraderService_GetProfitLoss_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goCryptoTraderServiceClient) TradeTokenBySignal(ctx context.Context, in *TradeTokenBySignalRequest, opts ...grpc.CallOption) (*TradeTokenBySignalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TradeTokenBySignalResponse)
	err := c.cc.Invoke(ctx, GoCryptoTraderService_TradeTokenBySignal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goCryptoTraderServiceClient) StopSignalMonitor(ctx context.Context, in *StopSignalMonitorRequest, opts ...grpc.CallOption) (*StopSignalMonitorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopSignalMonitorResponse)
	err := c.cc.Invoke(ctx, GoCryptoTraderService_StopSignalMonitor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goCryptoTraderServiceClient) MonitorPrice(ctx context.Context, in *MonitorPriceRequest, opts ...grpc.CallOption) (*MonitorPriceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MonitorPriceResponse)
	err := c.cc.Invoke(ctx, GoCryptoTraderService_MonitorPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoCryptoTraderServiceServer is the server API for GoCryptoTraderService service.
// All implementations must embed UnimplementedGoCryptoTraderServiceServer
// for forward compatibility.
type GoCryptoTraderServiceServer interface {
	GetInfo(context.Context, *GetInfoRequest) (*GetInfoResponse, error)
	GetRPCEndpoints(context.Context, *GetRPCEndpointsRequest) (*GetRPCEndpointsResponse, error)
	GetAccounts(context.Context, *GetAccountsRequest) (*GetAccountsResponse, error)
	GetTokenPrice(context.Context, *GetTokenPriceRequest) (*GetTokenPriceResponse, error)
	Crypto(context.Context, *CryptoRequest) (*CryptoResponse, error)
	TransferSOL(context.Context, *TransferSOLRequest) (*TransferSOLResponse, error)
	TransferToken(context.Context, *TransferTokenRequest) (*TransferTokenResponse, error)
	StartAutoTrade(context.Context, *StartAutoTradeRequest) (*StartAutoTradeResponse, error)
	StopAutoTrade(context.Context, *StopAutoTradeRequest) (*StopAutoTradeResponse, error)
	BuySOLToken(context.Context, *BuySOLTokenRequest) (*BuySOLTokenResponse, error)
	StopSOLTokenMonitor(context.Context, *StopAutoTradeRequest) (*StopAutoTradeResponse, error)
	GetProfitLoss(context.Context, *GetProfitLossRequest) (*GetProfitLossResponse, error)
	TradeTokenBySignal(context.Context, *TradeTokenBySignalRequest) (*TradeTokenBySignalResponse, error)
	StopSignalMonitor(context.Context, *StopSignalMonitorRequest) (*StopSignalMonitorResponse, error)
	MonitorPrice(context.Context, *MonitorPriceRequest) (*MonitorPriceResponse, error)
	mustEmbedUnimplementedGoCryptoTraderServiceServer()
}

// UnimplementedGoCryptoTraderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGoCryptoTraderServiceServer struct{}

func (UnimplementedGoCryptoTraderServiceServer) GetInfo(context.Context, *GetInfoRequest) (*GetInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInfo not implemented")
}
func (UnimplementedGoCryptoTraderServiceServer) GetRPCEndpoints(context.Context, *GetRPCEndpointsRequest) (*GetRPCEndpointsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRPCEndpoints not implemented")
}
func (UnimplementedGoCryptoTraderServiceServer) GetAccounts(context.Context, *GetAccountsRequest) (*GetAccountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccounts not implemented")
}
func (UnimplementedGoCryptoTraderServiceServer) GetTokenPrice(context.Context, *GetTokenPriceRequest) (*GetTokenPriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTokenPrice not implemented")
}
func (UnimplementedGoCryptoTraderServiceServer) Crypto(context.Context, *CryptoRequest) (*CryptoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Crypto not implemented")
}
func (UnimplementedGoCryptoTraderServiceServer) TransferSOL(context.Context, *TransferSOLRequest) (*TransferSOLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferSOL not implemented")
}
func (UnimplementedGoCryptoTraderServiceServer) TransferToken(context.Context, *TransferTokenRequest) (*TransferTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferToken not implemented")
}
func (UnimplementedGoCryptoTraderServiceServer) StartAutoTrade(context.Context, *StartAutoTradeRequest) (*StartAutoTradeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartAutoTrade not implemented")
}
func (UnimplementedGoCryptoTraderServiceServer) StopAutoTrade(context.Context, *StopAutoTradeRequest) (*StopAutoTradeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopAutoTrade not implemented")
}
func (UnimplementedGoCryptoTraderServiceServer) BuySOLToken(context.Context, *BuySOLTokenRequest) (*BuySOLTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BuySOLToken not implemented")
}
func (UnimplementedGoCryptoTraderServiceServer) StopSOLTokenMonitor(context.Context, *StopAutoTradeRequest) (*StopAutoTradeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopSOLTokenMonitor not implemented")
}
func (UnimplementedGoCryptoTraderServiceServer) GetProfitLoss(context.Context, *GetProfitLossRequest) (*GetProfitLossResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProfitLoss not implemented")
}
func (UnimplementedGoCryptoTraderServiceServer) TradeTokenBySignal(context.Context, *TradeTokenBySignalRequest) (*TradeTokenBySignalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TradeTokenBySignal not implemented")
}
func (UnimplementedGoCryptoTraderServiceServer) StopSignalMonitor(context.Context, *StopSignalMonitorRequest) (*StopSignalMonitorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopSignalMonitor not implemented")
}
func (UnimplementedGoCryptoTraderServiceServer) MonitorPrice(context.Context, *MonitorPriceRequest) (*MonitorPriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MonitorPrice not implemented")
}
func (UnimplementedGoCryptoTraderServiceServer) mustEmbedUnimplementedGoCryptoTraderServiceServer() {}
func (UnimplementedGoCryptoTraderServiceServer) testEmbeddedByValue()                               {}

// UnsafeGoCryptoTraderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoCryptoTraderServiceServer will
// result in compilation errors.
type UnsafeGoCryptoTraderServiceServer interface {
	mustEmbedUnimplementedGoCryptoTraderServiceServer()
}

func RegisterGoCryptoTraderServiceServer(s grpc.ServiceRegistrar, srv GoCryptoTraderServiceServer) {
	// If the following call pancis, it indicates UnimplementedGoCryptoTraderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GoCryptoTraderService_ServiceDesc, srv)
}

func _GoCryptoTraderService_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoCryptoTraderServiceServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoCryptoTraderService_GetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoCryptoTraderServiceServer).GetInfo(ctx, req.(*GetInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoCryptoTraderService_GetRPCEndpoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRPCEndpointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoCryptoTraderServiceServer).GetRPCEndpoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoCryptoTraderService_GetRPCEndpoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoCryptoTraderServiceServer).GetRPCEndpoints(ctx, req.(*GetRPCEndpointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoCryptoTraderService_GetAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoCryptoTraderServiceServer).GetAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoCryptoTraderService_GetAccounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoCryptoTraderServiceServer).GetAccounts(ctx, req.(*GetAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoCryptoTraderService_GetTokenPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTokenPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoCryptoTraderServiceServer).GetTokenPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoCryptoTraderService_GetTokenPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoCryptoTraderServiceServer).GetTokenPrice(ctx, req.(*GetTokenPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoCryptoTraderService_Crypto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CryptoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoCryptoTraderServiceServer).Crypto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoCryptoTraderService_Crypto_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoCryptoTraderServiceServer).Crypto(ctx, req.(*CryptoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoCryptoTraderService_TransferSOL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferSOLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoCryptoTraderServiceServer).TransferSOL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoCryptoTraderService_TransferSOL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoCryptoTraderServiceServer).TransferSOL(ctx, req.(*TransferSOLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoCryptoTraderService_TransferToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoCryptoTraderServiceServer).TransferToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoCryptoTraderService_TransferToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoCryptoTraderServiceServer).TransferToken(ctx, req.(*TransferTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoCryptoTraderService_StartAutoTrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartAutoTradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoCryptoTraderServiceServer).StartAutoTrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoCryptoTraderService_StartAutoTrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoCryptoTraderServiceServer).StartAutoTrade(ctx, req.(*StartAutoTradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoCryptoTraderService_StopAutoTrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopAutoTradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoCryptoTraderServiceServer).StopAutoTrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoCryptoTraderService_StopAutoTrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoCryptoTraderServiceServer).StopAutoTrade(ctx, req.(*StopAutoTradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoCryptoTraderService_BuySOLToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuySOLTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoCryptoTraderServiceServer).BuySOLToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoCryptoTraderService_BuySOLToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoCryptoTraderServiceServer).BuySOLToken(ctx, req.(*BuySOLTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoCryptoTraderService_StopSOLTokenMonitor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopAutoTradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoCryptoTraderServiceServer).StopSOLTokenMonitor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoCryptoTraderService_StopSOLTokenMonitor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoCryptoTraderServiceServer).StopSOLTokenMonitor(ctx, req.(*StopAutoTradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoCryptoTraderService_GetProfitLoss_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfitLossRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoCryptoTraderServiceServer).GetProfitLoss(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoCryptoTraderService_GetProfitLoss_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoCryptoTraderServiceServer).GetProfitLoss(ctx, req.(*GetProfitLossRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoCryptoTraderService_TradeTokenBySignal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TradeTokenBySignalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoCryptoTraderServiceServer).TradeTokenBySignal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoCryptoTraderService_TradeTokenBySignal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoCryptoTraderServiceServer).TradeTokenBySignal(ctx, req.(*TradeTokenBySignalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoCryptoTraderService_StopSignalMonitor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopSignalMonitorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoCryptoTraderServiceServer).StopSignalMonitor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoCryptoTraderService_StopSignalMonitor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoCryptoTraderServiceServer).StopSignalMonitor(ctx, req.(*StopSignalMonitorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoCryptoTraderService_MonitorPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MonitorPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoCryptoTraderServiceServer).MonitorPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoCryptoTraderService_MonitorPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoCryptoTraderServiceServer).MonitorPrice(ctx, req.(*MonitorPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GoCryptoTraderService_ServiceDesc is the grpc.ServiceDesc for GoCryptoTraderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoCryptoTraderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gctrpc.GoCryptoTraderService",
	HandlerType: (*GoCryptoTraderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _GoCryptoTraderService_GetInfo_Handler,
		},
		{
			MethodName: "GetRPCEndpoints",
			Handler:    _GoCryptoTraderService_GetRPCEndpoints_Handler,
		},
		{
			MethodName: "GetAccounts",
			Handler:    _GoCryptoTraderService_GetAccounts_Handler,
		},
		{
			MethodName: "GetTokenPrice",
			Handler:    _GoCryptoTraderService_GetTokenPrice_Handler,
		},
		{
			MethodName: "Crypto",
			Handler:    _GoCryptoTraderService_Crypto_Handler,
		},
		{
			MethodName: "TransferSOL",
			Handler:    _GoCryptoTraderService_TransferSOL_Handler,
		},
		{
			MethodName: "TransferToken",
			Handler:    _GoCryptoTraderService_TransferToken_Handler,
		},
		{
			MethodName: "StartAutoTrade",
			Handler:    _GoCryptoTraderService_StartAutoTrade_Handler,
		},
		{
			MethodName: "StopAutoTrade",
			Handler:    _GoCryptoTraderService_StopAutoTrade_Handler,
		},
		{
			MethodName: "BuySOLToken",
			Handler:    _GoCryptoTraderService_BuySOLToken_Handler,
		},
		{
			MethodName: "StopSOLTokenMonitor",
			Handler:    _GoCryptoTraderService_StopSOLTokenMonitor_Handler,
		},
		{
			MethodName: "GetProfitLoss",
			Handler:    _GoCryptoTraderService_GetProfitLoss_Handler,
		},
		{
			MethodName: "TradeTokenBySignal",
			Handler:    _GoCryptoTraderService_TradeTokenBySignal_Handler,
		},
		{
			MethodName: "StopSignalMonitor",
			Handler:    _GoCryptoTraderService_StopSignalMonitor_Handler,
		},
		{
			MethodName: "MonitorPrice",
			Handler:    _GoCryptoTraderService_MonitorPrice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}
